#!/bin/csh -f

# making sure we're using the right compiler
setenv CC gcc
setenv CXX g++

rm -rf cadmeshBuild
mkdir cadmeshBuild
cd cadmeshBuild


# setting
set ncpu = `getconf _NPROCESSORS_ONLN`
set opt = " -j"$ncpu" "

echo
echo Compiling with options $opt
echo

case $( uname -s) in
	Linux)
		sed -i '/geant4_set_and_check_package_variable(EXPAT_LIBRARY ""  "")/s/^/#/' $G4INSTALL/lib/Geant4-$G4_VERSION/Geant4PackageCache.cmake
		;;
	Darwin)
		/usr/bin/sed -i '' '/geant4_set_and_check_package_variable(EXPAT_LIBRARY ""  "")/s/^/#/' $G4INSTALL/lib/Geant4-$G4_VERSION/Geant4PackageCache.cmake
		;;
	*)
		echo "Unsupported OS: $(uname -s)"
		exit 1
		;;
esac

cmake ../cadmesh -DCMAKE_INSTALL_PREFIX:PATH=$MLIBRARY
make $opt install
echo done
