from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")
env.Append(CXXFLAGS = ' -std=c++11 ')
lib = env.Library(source = "frequencySyncSignal.cc", target = "../lib/frequencySyncSignal")

